# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='plan',
            new_name='description',
        ),
    ]
